# SPDX-License-Identifier: GPL-2.0-only
# Workstation ~/.snajpagent/config.ini, or snajpagent remote --config PATH COMMAND...
# Only [terminal] is read by remote mode. The default is ~/Downloads.
[terminal]
download_dir = ~/Downloads
