#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Generate the VM's Unicode 17 tables from pinned official UCD inputs.

Normal builds use the checked-in table and require no network. Regeneration:
  python3 tools/generate_unicode.py --fetch --data-dir build/unicode-17.0.0
"""
import argparse
from array import array
import hashlib
from pathlib import Path
from urllib.request import urlopen

INPUTS = {
    'auxiliary/GraphemeBreakProperty.txt': 'd6b51d1d2ae5c33b451b7ed994b48f1f4dc62b2272a5831e7fd418514a6bae89',
    'auxiliary/GraphemeBreakTest.txt': 'e2d134d2c52919bace503ebb6a551c1855fe1a1faec18478c78fff254a1793ec',
    'DerivedCoreProperties.txt': '24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08',
    'emoji/emoji-data.txt': '2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b',
    'EastAsianWidth.txt': 'ea7ce50f3444a050333448dffef1cadd9325af55cbb764b4a2280faf52170a33',
    'extracted/DerivedGeneralCategory.txt': 'd62e5bab70ca74f099343f71224fa051cb1fdd61a1ab45c0488c44cfc0b6102e',
}
GCB = dict(Other=0, CR=1, LF=2, Control=3, Extend=4, ZWJ=5, Regional_Indicator=6,
           Prepend=7, SpacingMark=8, L=9, V=10, T=11, LV=12, LVT=13)
INCB = dict(Consonant=1, Extend=2, Linker=3)
ROOT = Path(__file__).resolve().parent.parent


def records(text):
    for line in text.splitlines():
        body = line.split('#', 1)[0].strip()
        if not body:
            continue
        span, *properties = (word.strip() for word in body.split(';'))
        bounds = span.split('..')
        yield int(bounds[0], 16), int(bounds[-1], 16), properties


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--data-dir', type=Path, required=True)
    parser.add_argument('--fetch', action='store_true')
    args = parser.parse_args()
    args.data_dir.mkdir(parents=True, exist_ok=True)
    sources = {}
    for name, expected in INPUTS.items():
        path = args.data_dir / Path(name).name
        if not path.exists() and args.fetch:
            url = 'https://www.unicode.org/Public/17.0.0/ucd/' + name
            path.write_bytes(urlopen(url, timeout=30).read())
        data = path.read_bytes()
        if hashlib.sha256(data).hexdigest() != expected:
            raise SystemExit('Unicode source checksum mismatch: ' + str(path))
        sources[Path(name).name] = data.decode('utf-8')
    values = array('H', [0]) * 0x110000
    for name, text in sources.items():
        if name == 'GraphemeBreakTest.txt':
            continue
        for low, high, props in records(text):
            bits = 0
            if name == 'GraphemeBreakProperty.txt':
                if props[0] in ('LV', 'LVT'):
                    continue  # Hangul syllables use their arithmetic definition.
                bits = GCB[props[0]]
            elif name == 'DerivedCoreProperties.txt' and props[0] == 'InCB':
                bits = INCB[props[1]] << 4
            elif name == 'emoji-data.txt':
                bits = {'Extended_Pictographic': 0x40, 'Emoji_Presentation': 0x80}.get(props[0], 0)
            elif name == 'EastAsianWidth.txt':
                bits = {'W': 0x100, 'F': 0x100, 'A': 0x200}.get(props[0], 0)
            elif name == 'DerivedGeneralCategory.txt':
                if props[0] in ('Mn', 'Mc', 'Me', 'Cf'):
                    bits |= 0x400
                if props[0][0] in ('L', 'N'):
                    bits |= 0x800
                if props[0][0] == 'Z':
                    bits |= 0x1000
            if bits:
                for cp in range(low, high + 1):
                    values[cp] |= bits
    output = ['/* SPDX-License-Identifier: Unicode-3.0 */',
              '/* Generated by tools/generate_unicode.py from Unicode 17.0.0.',
              ' * Copyright Unicode, Inc. See COPYING.UNICODE and LICENSE_SCOPE.',
              ' * Source URLs and SHA256 values are pinned in the generator. */',
              'static const struct unicode_range unicode_ranges[] = {']
    low = 0
    for cp in range(1, len(values) + 1):
        if cp == len(values) or values[cp] != values[low]:
            if values[low]:
                output.append(f'    {{0x{low:x}u, 0x{cp - 1:x}u, 0x{values[low]:x}u}},')
            low = cp
    output.append('};')
    (ROOT / 'src/unicode_tables.inc').write_text('\n'.join(output) + '\n')
    fixture = ROOT / 'tests/fixtures/unicode-17.0.0'
    fixture.mkdir(parents=True, exist_ok=True)
    normalized = '\n'.join(line.rstrip() for line in sources['GraphemeBreakTest.txt'].splitlines())
    (fixture / 'GraphemeBreakTest.txt').write_text(
        '# SPDX-License-Identifier: Unicode-3.0\n'
        '# Generated from the pinned official file; trailing comment whitespace normalized.\n'
        + normalized + '\n')
    print('unicode: generated', len(output) - 6, 'property ranges')


if __name__ == '__main__':
    main()
