/* SPDX-License-Identifier: GPL-2.0-only */
#include "commands.h"

const struct snag_term_command snag_commands[] = {
    {"/help", "commands and keys (alias /?)"},
    {"/?", "same as /help"},
    {"/status", "session and next-turn settings"},
    {"/config", "edit/reload configuration at a safe boundary"},
    {"/mcp list", "list configured native MCP servers"},
    {"/mcp status SERVER", "MCP protocol, credential and catalog diagnostics"},
    {"/mcp tools SERVER", "inspect exact remote tool declarations and filtering"},
    {"/mcp reload SERVER", "refresh the catalog at the next turn boundary"},
    {"/mcp login SERVER", "show the private CLI OAuth login command"},
    {"/mcp logout SERVER", "revoke and remove a server's OAuth credential"},
    {"/mcp pending [DIGEST]", "inspect complete approval-gated MCP arguments"},
    {"/mcp approve DIGEST", "approve exactly one matching pending MCP call"},
    {"/mcp deny DIGEST", "remove a pending MCP approval"},
    {"/configure", "reload saved configuration, credentials and model cache"},
    {"/verbose [0..6]", "show/set verbosity for this process"},
    {"/banner [TEXT|clear]", "show/set session banner echoed in later requests"},
    {"/model [list|cache]", "list cached models; cache refreshes all providers"},
    {"/model [#]N[:CONTEXT] [save|s]", "select numbered model/effort row (N starts at 1)"},
    {"/model MODEL[/EFFORT][:CONTEXT] [save|s]", "select on the next-turn provider"},
    {"/model PROVIDER/MODEL/EFFORT[:CONTEXT] [save|s]", "select explicit provider/model/effort"},
    {"/fallback [SELECTOR|off] [save|s]", "configure automatic fallback on terminal cyber_policy"},
    {"/fast [on|off|status]", "toggle fast service; retain the selected model and effort"},
    {"/effort [LEVEL]", "show/set provider-defined effort (default means medium)"},
    {"/context", "show the context window, its reserve and compaction budget"},
    {"/context default", "use the configured or advertised working window"},
    {"/context max", "use the advertised maximum context"},
    {"/context N [s|save]", "set N tokens; optionally save this model's config default"},
    {"/compact", "compact context at a safe request boundary"},
    {"/state", "session state including goal and its actions"},
    {"/state goal [status|help]", "show goal section or this usage"},
    {"/state goal [set] TEXT", "start/reword goal; set accepts reserved first words"},
    {"/state goal \"TEXT\"", "start/reword with quoted wording"},
    {"/state goal pause|resume", "stop/restart automatic continuation"},
    {"/state goal lock|unlock", "prevent/allow model rewording"},
    {"/state goal complete|cancel|clear", "end goal; clear=cancel; current turn finishes"},
    {"/goal ...", "alias for /state goal ..."},
    {"/ro QUERY", "one read-only turn; queued during active work"},
    {"/queue [TEXT]", "list/add future turns (alias /q)"},
    {"/queue clear|c", "remove all queued turns"},
    {"/queue pop|p", "remove newest queued turn"},
    {"/queue N delete|d", "remove queued turn N (N starts at 1)"},
    {"/queue N edit|e", "edit queued turn N in the composer"},
    {"/queue Nd|Ne", "short forms of N delete / N edit"},
    {"/next", "run oldest paused turn; arm queue if active"},
    {"/retry", "retry failed turn; if active, restart at a safe boundary"},
    {"/retry auto [on|off]", "toggle automatic retries or set the saved session preference"},
    {"/yield", "return tool wait to model; keep running processes"},
    {"/session", "current session ID and running sessions"},
    {"/session list|l", "all saved sessions and their attachment state"},
    {"/session name NAME", "set the current session's saved name"},
    {"/session attach|a ID", "switch to a live session; failure keeps this attachment"},
    {"/session detach|d", "return to the shell while this session continues"},
    {"/s [list|l|name NAME|attach|a ID|detach|d]", "alias for /session"},
    {"/history [N]", "show N retained turns; default 1, 0 counts only"},
    {"/delete", "delete after confirmation at a safe boundary"},
    {"/exit", "stop work, preserve session and exit"},
    {"/cat PATH", "open a local file in the configured pager"},
    {"/receive [-d]", "receive workstation files as unsent attachments"},
    {"/send PATH", "send one file to the workstation through trzsz"},
    {"/attach PATH", "prepare an image or retain a media/document file for the next private input"},
    {"/attachments", "list unsent attachments"},
    {"/detach N|all", "remove unsent attachments"},
    {"/dictate", "capture up to 60s; Enter finishes, Escape cancels; insert transcript into draft"},
    {"/voice on", "start explicit live voice using the configured API route"},
    {"/voice off", "close voice; coding work keeps its existing owner"},
    {"/voice mute", "stop microphone forwarding; /voice unmute resumes fresh audio"},
    {"/voice devices", "list exact capture and playback device names"},
    {"/play asset:ID", "play the first 60s of an accepted audio asset; /play stop interrupts"},
    {"/chat [ADDRESS]", "show the selected or addressed channel"},
    {"/rollout", "show local model activity"},
    {"/query [ADDRESS [TEXT]]", "open a private chat; no address lists opened queries"},
    {"/connections [SESSION|ADDRESS]", "list connections or open SESSION/ENDPOINT/"},
    {"/whois [NICK]", "inspect a nick on the selected connection"},
    {"/msg ADDRESS TEXT", "send to a nick or channel without changing tabs"},
    {"/notice ADDRESS TEXT", "send a notice to a nick or channel"},
    {"/me TEXT", "send an action to the selected operator conversation"},
    {"/join ADDRESS", "join a channel as the operator and open its conversation"},
    {"/part [ADDRESS [REASON]]", "leave the selected or addressed operator channel"},
    {"/topic [TEXT]", "show/set selected room topic"},
    {"/nick [NICK]", "show nicks/set your operator nick (shared via IRC)"},
    {"/steering [mentions|all|clear]", "show/set steering admission for next turn"},
    {"/names", "numbered destinations, members and modes"},
    {"/server [start [ENDPOINT]|stop]", "show/start/stop hosting; default localhost:6667"},
    {"/connect [ENDPOINT]", "add outgoing connection; default localhost:6667"},
    {"/disconnect [ENDPOINT]", "remove one/all outgoing connections; keep hosting"},
    {"/N [TEXT]", "select destination N, or send there once"},
    {"/all TEXT", "send once to all destinations"},
};

size_t
snag_command_count(void)
{
    return sizeof(snag_commands) / sizeof(snag_commands[0]);
}
